[package]
name = "day7"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../lib" }
itertools = "0.13.0"
regex = "1.11.1"
tokio = { version = "1.42.0", features = ["full", "rt"] }
futures = "0.3.31"
futures-util = "0.3.31"